In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 设置画图风格
sns.set_theme(style="whitegrid")

# 读取数据，注意把第一列作为索引（解决作业里提到的“无实际预测意义的索引字段”问题）
# 请确保你的路径是正确的
df = pd.read_csv('../data/cs-training.csv', index_col=0)

# 查看前几行、行列数、数据类型
print(f"数据形状: {df.shape}")
display(df.head())
display(df.info())

数据形状: (150000, 11)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

<class 'pandas.core.frame.DataFrame'>
Index: 150000 entries, 1 to 150000
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

None

In [3]:
import pandas as pd
#用 pandas 读入数据。检查前几行、行列数、字段名、数据类型。注意：CSV 里可能有一列无实际预测意义的索引字段；先识别它，不要直接把它当特征。
df=pd.read_csv('../data/cs-training.csv', index_col=0)
df.head(10)
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 150000 entries, 1 to 150000
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [14]:
'''统计每列缺失数量和比例。
统计目标变量的类别数量和比例。
把缺失值结果按比例排序，写出你观察到的两点。
记录目标类别是否不平衡，以及这会怎样影响后续评价模型。
'''
missing_data=pd.DataFrame({
    '缺失数量':df.isnull().sum(),
    '缺失比例':(df.isnull().sum()/len(df))*100
})

missing_data=missing_data[missing_data['缺失数量']>0].sort_values(by='缺失比例',ascending=False)

print(missing_data)

                     缺失数量       缺失比例
MonthlyIncome       29731  19.820667
NumberOfDependents   3924   2.616000

In [7]:
# 1. 创建一个 DataFrame 集中管理
missing_data = pd.DataFrame({
    '缺失数量': df.isnull().sum(),
    '缺失比例(%)': (df.isnull().sum() / len(df)) * 100
})

# 2. 过滤掉没有缺失值的列，并按照缺失比例降序排列
missing_data = missing_data[missing_data['缺失数量'] > 0].sort_values(by='缺失比例(%)', ascending=False)

# 3. 打印结果
print(missing_data)

                     缺失数量    缺失比例(%)
MonthlyIncome       29731  19.820667
NumberOfDependents   3924   2.616000

monthlyincome的缺失比例明显较高，需进一步了解缺失情况，若无较合理的填充值，后续应删除对应行。
NumberOfDependents缺失比例只有2%，较少，可以直接删除对应行。